CREATE TABLE m0_source_documents (sha256 text PRIMARY KEY CHECK(sha256 ~ '^[0-9a-f]{64}$'), schema_version text NOT NULL DEFAULT 'm0', bytes bytea NOT NULL, byte_size bigint NOT NULL, media_type text NOT NULL, encoding text, retention_class text NOT NULL, recorded_at timestamptz NOT NULL);
--> statement-breakpoint
CREATE TABLE m0_acquisition_attempts (id uuid PRIMARY KEY, schema_version text NOT NULL DEFAULT 'm0', source text NOT NULL, source_policy_version text NOT NULL, method text NOT NULL, resource text NOT NULL, requested_at timestamptz NOT NULL, completed_at timestamptz NOT NULL, observed_at timestamptz NOT NULL, http_status bigint, etag text, last_modified text, byte_size bigint, media_type text, document_sha256 text REFERENCES m0_source_documents(sha256), failure jsonb, recorded_at timestamptz NOT NULL, CHECK(document_sha256 IS NOT NULL OR failure IS NOT NULL OR COALESCE(http_status = 304, false)));
--> statement-breakpoint
CREATE TABLE m0_parse_runs (id uuid PRIMARY KEY, schema_version text NOT NULL DEFAULT 'm0', document_sha256 text NOT NULL REFERENCES m0_source_documents(sha256), parser text NOT NULL, parser_version text NOT NULL, status text NOT NULL CHECK(status IN ('succeeded','partial','failed')), failure jsonb, started_at timestamptz NOT NULL, completed_at timestamptz NOT NULL, recorded_at timestamptz NOT NULL, CHECK((status = 'succeeded') = (failure IS NULL)));
--> statement-breakpoint
CREATE TABLE m0_form4_transaction_facts (id uuid PRIMARY KEY, schema_version text NOT NULL DEFAULT 'm0', parse_run_id uuid NOT NULL REFERENCES m0_parse_runs(id), document_sha256 text NOT NULL REFERENCES m0_source_documents(sha256), accession text NOT NULL, issuer_cik text NOT NULL CHECK(issuer_cik ~ '^[0-9]{10}$'), issuer_name text NOT NULL, issuer_ticker text, reporting_owner_cik text NOT NULL CHECK(reporting_owner_cik ~ '^[0-9]{10}$'), reporting_owner_name text NOT NULL, is_director boolean NOT NULL, is_officer boolean NOT NULL, is_ten_percent_owner boolean NOT NULL, accepted_at timestamptz NOT NULL, transaction_date text NOT NULL CHECK(transaction_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'), security_title text NOT NULL, transaction_code text NOT NULL, acquired_disposed text NOT NULL, ownership text NOT NULL, shares numeric NOT NULL CHECK(shares >= 0), price_per_share numeric NOT NULL CHECK(price_per_share >= 0), footnote_refs text[] NOT NULL, source_locator text NOT NULL, observed_at timestamptz NOT NULL, recorded_at timestamptz NOT NULL, UNIQUE(document_sha256, source_locator));
--> statement-breakpoint
CREATE TABLE m0_issuers (id uuid PRIMARY KEY, schema_version text NOT NULL DEFAULT 'm0', cik text NOT NULL CHECK(cik ~ '^[0-9]{10}$'), legal_name text NOT NULL, effective_from text NOT NULL, effective_to text, recorded_at timestamptz NOT NULL, UNIQUE(cik,effective_from), CHECK(effective_to IS NULL OR effective_to > effective_from));
--> statement-breakpoint
CREATE TABLE m0_listings (id uuid PRIMARY KEY, schema_version text NOT NULL DEFAULT 'm0', issuer_id uuid NOT NULL REFERENCES m0_issuers(id), ticker text NOT NULL, venue text NOT NULL, security_type text NOT NULL, effective_from text NOT NULL, effective_to text, recorded_at timestamptz NOT NULL, CHECK(effective_to IS NULL OR effective_to > effective_from));
--> statement-breakpoint
CREATE TABLE m0_broker_assets (id uuid PRIMARY KEY, schema_version text NOT NULL DEFAULT 'm0', listing_id uuid NOT NULL REFERENCES m0_listings(id), broker text NOT NULL, broker_asset_id text NOT NULL, symbol text NOT NULL, tradable boolean NOT NULL, fractionable boolean NOT NULL, effective_from text NOT NULL, effective_to text, recorded_at timestamptz NOT NULL, UNIQUE(broker,broker_asset_id,effective_from), CHECK(effective_to IS NULL OR effective_to > effective_from));
--> statement-breakpoint
CREATE TABLE m0_sip_daily_bars (schema_version text NOT NULL DEFAULT 'm0', acquisition_attempt_id uuid NOT NULL REFERENCES m0_acquisition_attempts(id), listing_id uuid NOT NULL REFERENCES m0_listings(id), session_date text NOT NULL, feed text NOT NULL CHECK(feed='sip'), adjustment text NOT NULL, open numeric NOT NULL CHECK(open>=0), high numeric NOT NULL CHECK(high>=0), low numeric NOT NULL CHECK(low>=0), close numeric NOT NULL CHECK(close>=0), volume numeric NOT NULL CHECK(volume>=0), vwap numeric CHECK(vwap>=0), observed_at timestamptz NOT NULL, recorded_at timestamptz NOT NULL, PRIMARY KEY(listing_id,session_date,feed,adjustment));
--> statement-breakpoint
CREATE TABLE m0_market_sessions (id uuid PRIMARY KEY, schema_version text NOT NULL DEFAULT 'm0', acquisition_attempt_id uuid NOT NULL REFERENCES m0_acquisition_attempts(id), calendar_version text NOT NULL, session_date text NOT NULL, opens_at timestamptz NOT NULL, closes_at timestamptz NOT NULL, early_close boolean NOT NULL, source text NOT NULL, observed_at timestamptz NOT NULL, recorded_at timestamptz NOT NULL, UNIQUE(calendar_version,session_date), CHECK(opens_at < closes_at));
--> statement-breakpoint
CREATE TABLE m0_runtime_checkpoints (key text PRIMARY KEY, value jsonb NOT NULL, updated_at timestamptz NOT NULL, ledger_cursor bigint NOT NULL DEFAULT 0);
--> statement-breakpoint
CREATE TABLE m0_job_run_events (cursor bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, id uuid NOT NULL UNIQUE, schema_version text NOT NULL DEFAULT 'm0', run_id uuid NOT NULL, job text NOT NULL, lane text NOT NULL CHECK(lane IN ('ordinary','priority')), event text NOT NULL CHECK(event IN ('started','finished','failed','skipped-overlap')), at timestamptz NOT NULL, outcome text, meta jsonb NOT NULL, recorded_at timestamptz NOT NULL);
--> statement-breakpoint
CREATE TABLE m0_cockpit_events (cursor bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, schema_version text NOT NULL DEFAULT 'm0', kind text NOT NULL, artifact_id text NOT NULL, recorded_at timestamptz NOT NULL);
--> statement-breakpoint
CREATE OR REPLACE FUNCTION sonde_reject_m0_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION '% is append-only: % rejected', TG_TABLE_NAME, TG_OP USING ERRCODE='restrict_violation'; END; $$ LANGUAGE plpgsql;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION sonde_append_cockpit_event() RETURNS trigger AS $$ BEGIN INSERT INTO m0_cockpit_events(kind, artifact_id, recorded_at) VALUES (TG_ARGV[0], NEW.id::text, NEW.recorded_at); RETURN NEW; END; $$ LANGUAGE plpgsql;
--> statement-breakpoint
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['m0_source_documents','m0_acquisition_attempts','m0_parse_runs','m0_form4_transaction_facts','m0_issuers','m0_listings','m0_broker_assets','m0_sip_daily_bars','m0_market_sessions','m0_job_run_events','m0_cockpit_events'] LOOP EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION sonde_reject_m0_mutation()',t||'_append_only',t); END LOOP; END $$;
--> statement-breakpoint
CREATE TRIGGER m0_form4_cockpit AFTER INSERT ON m0_form4_transaction_facts FOR EACH ROW EXECUTE FUNCTION sonde_append_cockpit_event('form4-transaction-fact');
--> statement-breakpoint
CREATE TRIGGER m0_job_cockpit AFTER INSERT ON m0_job_run_events FOR EACH ROW EXECUTE FUNCTION sonde_append_cockpit_event('job-run-event');
