DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sonde_web') THEN
		CREATE ROLE sonde_web LOGIN PASSWORD 'sonde_web';
	END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO sonde_web;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO sonde_web;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sonde_web;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO sonde_web;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO sonde_web;
GRANT sonde_web TO CURRENT_USER;
